services:
  order-service:
    build: .
    container_name: order-service
    command: ["python3", "order_service.py"]
    depends_on:
      - kafka
    stdin_open: true
    tty: true

  payment-service:
    build: .
    container_name: payment-service
    command: ["python3", "payment_service.py"]
    depends_on:
      - kafka
    stdin_open: true
    tty: true

  delivery-service:
    build: .
    container_name: delivery-service
    command: ["python3", "delivery_service.py"]
    depends_on:
      - kafka
    stdin_open: true
    tty: true

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
